services:
  rabbit-mq-service:
    image: rabbitmq:3-management-alpine
    container_name: rabbit-mq-service
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "test-user"
      RABBITMQ_DEFAULT_PASS: "147248"

  postgres-service:
    image: postgres:11.0
    container_name: postgres-service
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hvac_database

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - AMQP_HOST=${AMQP_HOST}
        - AMQP_URL=${AMQP_URL}
        - AMQP_USER=${AMQP_USER}
        - AMQP_PASS=${AMQP_PASS}
        - DATABASE_URL=${DATABASE_URL}
        - POSTGRES_USER=${POSTGRES_USER}
    links:
      - postgres-service
      - rabbit-mq-service
    depends_on:
      - rabbit-mq-service
      - postgres-service
    env_file:
      - .env
