version: "3.9"

services:
  rabbit-mq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: "test-user"
      RABBITMQ_DEFAULT_PASS: "147248"
  postgres:
    image: postgres:11.0
    ports:
      - '15432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
